name: Update

on:
  watch:
    types: started
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Version
        run: |
          echo $[$(cat .ver)+1] > .ver

      - name: Update rime-ice dicts
        run: |
          wget -O rime-ice.zip https://github.com/iDvel/rime-ice/archive/refs/heads/main.zip
          unzip rime-ice.zip
          cp -rf ./rime-ice-main/cn_dicts .
          cp -rf ./rime-ice-main/en_dicts .
          cp -rf ./rime-ice-main/opencc .
          rm -rf rime-ice-main rime-ice.zip

      - name: Update rime-lua-aux-code
        run: |
          wget -O aux-code.zip https://github.com/HowcanoeWang/rime-lua-aux-code/archive/refs/heads/main.zip
          unzip aux-code.zip
          cp -rf ./rime-lua-aux-code-main/lua/aux_code.lua ./lua/aux_code
          cp -rf ./rime-lua-aux-code-main/lua/flypy_full.txt ./lua/aux_code
          rm -rf rime-lua-aux-code-main aux-code.zip

      - name: Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "d"
          git remote rm origin
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin main
