name: Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update rime-ice dicts
        run: |
          wget -O rime-ice.zip https://github.com/iDvel/rime-ice/archive/refs/heads/main.zip
          unzip rime-ice.zip
          files=(cn_dicts en_dicts opencc)
          for item in "${files[@]}"
          do
              cp -rf ./rime-ice-main/$item .
          done
          rm -rf rime-ice-main rime-ice.zip
          echo "[Info] Update Completed!"

      - name: Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "d"
          git remote rm origin
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push
